name: Release

on:
  push:
    branches:
      - master
      - beta
      - alpha

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: '15.x'

      - name: Install dependencies
        run: npm ci

      - name: Release
        use: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}