name: Test

on:
  push:
    branches: [ 'pr/**' ]
  pull_request:
    branches: [ 'pr/**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npm run test