name: Validate Push/PR

on:
  push:
    branches: [ 'pr/**' ]
  pull_request:
    branches: [ 'pr/**' ]

jobs:
  commitlint:
    name: Lint commits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: '15.x'

      - name: Install dependencies
        run: npm ci

      - name: Commitlint
        run: 'npx commitlint --from HEAD~1 --to HEAD --verbose'

  test-app:
    name: Integration and unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: '15.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:app

  test-e2e:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    name: End-to-end test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'

      - name: Install dependencies
        run: npm ci

      - name: Run test server
        run: npm run develop

      - name: Run tests
        run: npm run test:e2e
