name: Validate Push/PR

on:
  push:
    branches: [ 'pr/**' ]
  pull_request:
    branches: [ 'pr/**' ]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: '15.x'

      - name: Install dependencies
        run: npm ci

      - name: Commitlint
        run: 'npx commitlint --from HEAD~1 --to HEAD --verbose'

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: '15.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test